global:
templates:
route:
  receiver: default
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by:
  - alertname
  routes: []
receivers:
- name: default
  slack_configs:
  - api_url: SLACK_WEBHOOK_URL
    channel: alert
    send_resolved: true